dist: trusty
addons:
  chrome: stable
language: python
python:
- '3.5'
before_install:
- wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/local/bin
- sudo chmod a+x /usr/local/bin/chromedriver
install:
- pip install -r requirements.txt
- pip install coveralls
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
- coverage run --source=flash setup.py test
after_success: coveralls
deploy:
  - provider: cloudfoundry
    edge: true
    api: https://api.run.pez.pivotal.io
    username: $CF_USERNAME
    password: $CF_PASSWORD
    organization: pivot-jsharpe
    space: flash
    manifest: manifest.yml
