dist: xenial
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
services:
  - xvfb

language: python
python:
- '3.7'

before_install:
- wget https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/local/bin
- sudo chmod a+x /usr/local/bin/chromedriver

install:
- pip install -r requirements.txt
- pip install coveralls

script: coverage run --source=flash setup.py test

after_success: coveralls

deploy:
  - provider: cloudfoundry
    edge: true
    api: https://api.run.pivotal.io
    username: $CF_USERNAME
    password: $CF_PASSWORD
    organization: $CF_ORGANIZATION
    space: $CF_SPACE
    manifest: manifest.yml
